# Generated by Django 4.2.27 on 2026-01-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="occupancylog",
            name="precipitation",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name="occupancylog",
            name="pressure",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="occupancylog",
            name="traffic_index",
            field=models.IntegerField(default=0, help_text="0-10 scale"),
        ),
    ]
